### PR TITLE
feature: Use GitHub Actions for NuGet Releases

### PR DESCRIPTION
**Pull request by worldbeater**
This PR enables GitHub Actions for this repository. From now on, after a pull request marked with the `release` label is merged, a new `NuGet` package will be shipped and a new release with a change log will be published to GitHub Releases. Ideally, we should use the [Commit Prefixes](https://github.com/glennawatson/ChangeLog#commit-prefixes) and squash-and-merge strategy to enable automatic commit categorization in release notes.

The `yml` configuration is based on the configurations we use in [ReactiveUI.Validation](https://github.com/reactiveui/reactiveui.validation).

### CODE REVIEW

**Comment by worldbeater** [comment]
Hey @JaggerJo!

As we are moving Live.Avalonia to AvaloniaCommunity, I prepared a GitHub Actions configuration that would allow pushing a new NuGet package every time a PR marked with the [release] label is merged. We are using this setup in ReactiveUI organization e.g. in the [ReactiveUI.Validation](https://github.com/reactiveui/reactiveui.validation) repository. Package version is incremented automagically using NBGV and `version.json`.

Your input is required here. Someone with admin permission has to do a couple of things:
- [ ] create a new `release` label, so an arbitrary PR could be marked with that label
- [ ] define the `NUGET_API_KEY` variable in the repository secrets section https://github.com/AvaloniaCommunity/Live.Avalonia/settings/secrets/actions
- [ ] mark this PR with the `release` label and try merging

**Comment by JaggerJo** [comment]
@worldbeater you should have the required permissions now. 

Will look into doing the same for FuncUI 👍🏼

**Comment by worldbeater** [comment]
Thanks @JaggerJo!

I could try setting up GitHub Actions the same way for FuncUI and Prism.Avalonia if you're ok with that 🚀 

Mering this PR, going to try out the release process for Live.Avalonia now.

**Comment by worldbeater** [comment]
A new `Live.Avalonia` version has been successfully shipped 🎉 
The change log: https://github.com/AvaloniaCommunity/Live.Avalonia/releases/tag/1.1.1
The package: https://www.nuget.org/packages/Live.Avalonia/1.1.1

**Comment by AngelMunoz** [comment]
hey @worldbeater  I tried to add this workflow to https://github.com/AngelMunoz/Mondocks but... I seem to be doing something wrong because the workflow is not triggered, would you mind helping me figure it out 😅?

**Comment by worldbeater** [comment]
@AngelMunoz I guess that's due to the main branch being named `master` in the repo you are referencing, and the Github Actions config uses the `main` name. So I guess you should either [change the main branch name from `master` to `main`](https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main), or edit your Github Actions triggers config https://github.com/AngelMunoz/Mondocks/blob/master/.github/workflows/build.yml#L5 Immediately after you do this and open a new PR, Github Actions logs should become available here https://github.com/AngelMunoz/Mondocks/actions

**Comment by AngelMunoz** [comment]
😰 OH can't believe I didn't check the branch names 😅 I'll try that tomorrow morning asap thanks! Sorry for the bother

**Pull request merged**
